spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123!
token:
  secret:
    key: DiaryAPIJWTSecretKeyValueYangKangDuoplay
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
    properties:
      format_sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://diary-db:3306/diary?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/diary?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true