name: Build and Run API on Self-hosted Runner

# 풀리퀘스트를 통한 머지가 발생할때 실행
on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: self-hosted

    steps:
      # 최신 버전의 소스를 불러온다
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 스크립트 사용을 임시적으로 허용한다
      - name: Grant script permission
        run: Set-ExecutionPolicy RemoteSigned -Scope Process -Force

      # 프로젝트를 빌드한다
      - name: Build Project
        run: .\gradlew build

      # java 파일을 담을 디렉토리를 생성
      - name: Make directory
        run: mkdir .\api\deploy

      # 빌드 파일을 복사한다.
      - name: Copy jar
        run: cp -Force .\api\build\libs\*.jar .\api\deploy\api-latest.jar
