name: Build and Run API on Self-hosted Runner(Windows)

# 풀리퀘스트를 통한 머지가 발생할때 실행
on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: self-hosted

    steps:
      # 최신 버전의 소스를 불러온다
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 프로젝트를 빌드한다
      - name: Build Project
        id: build
        run: C:\actions-runner\_work\diary-app\diary-app\gradlew build
        
  run:
    runs-on: self-hosted

    steps:
      # 프로젝트를 실행한다
      - name: Run API
        run: java -jar C:\actions-runner\_work\diary-app\diary-app\api\build\libs\api-0.0.1-SNAPSHOT.jar
