name: Build and Run API on Self-hosted Runner(Windows)

# 풀리퀘스트를 통한 머지가 발생할때 실행
on:
  pull_request:
    types:
      - closed

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      # 최신 버전의 소스를 불러온다
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 프로젝트를 빌드한다
      - name: Build Project
        run: .\gradlew build

      # java 파일을 담을 디렉토리를 생성
      - name: Make directory
        run: mkdir .\api\deploy

      # 빌드 파일을 복사한다.
      - name: Copy jar
        run: cp -Force .\api\build\libs\*.jar .\api\deploy\api-latest.jar

      # 빌드된 파일을 백그라운드로 실행한다.
      - name: Run jar
        run: java -jar .\api\deploy\api-latest.jar
