name: Build and Run API on Self-hosted Runner

# 풀리퀘스트를 통한 머지 혹은 push가 발생할때 실행
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      # 최신 버전의 소스를 불러온다
      - name: Checkout Repository
        uses: actions/checkout@v4

      # .env 파일 복사
      - name: Copy .env File
        run: cp ~/env ./.env

      # 프로젝트를 빌드
      - name: Build Project
        run: ./gradlew build

      # docker On
      - name: docker on
        run: sudo docker compose up -d --build
